name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  formatting:
    name: Check formatting with dprint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run dprint check
        uses: dprint/check@v2.3

  rust:
    name: Build & Test Listings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build workspace
        run: cargo build --workspace --verbose
      - name: Run tests
        run: cargo test --workspace --verbose
